
const TELEPORTCITIES = {
  "Aarhus": "aarhus",
  "Adelaide": "adelaide",
  "Albuquerque": "albuquerque",
  "Almaty": "almaty",
  "Amsterdam": "amsterdam",
  "Anchorage": "anchorage",
  "Andorra": "andorra",
  "Ankara": "ankara",
  "Asheville": "asheville",
  "Asuncion": "asuncion",
  "Athens": "athens",
  "Atlanta": "atlanta",
  "Auckland": "auckland",
  "Austin": "austin",
  "Baku": "baku",
  "Bali": "bali",
  "Barcelona": "barcelona",
  "Beirut": "beirut",
  "Belfast": "belfast",
  "Belgrade": "belgrade",
  "Belize City": "belize-city",
  "Bengaluru": "bengaluru",
  "Bergen": "bergen",
  "Bern": "bern",
  "Birmingham": "birmingham",
  "Birmingham, AL": "birmingham-al",
  "Bogota": "bogota",
  "Boise": "boise",
  "Bologna": "bologna",
  "Bordeaux": "bordeaux",
  "Boston": "boston",
  "Boulder": "boulder",
  "Bozeman": "bozeman",
  "Bratislava": "bratislava",
  "Brighton": "brighton",
  "Brisbane": "brisbane",
  "Bristol": "bristol",
  "Brno": "brno",
  "Brussels": "brussels",
  "Bucharest": "bucharest",
  "Budapest": "budapest",
  "Buffalo": "buffalo",
  "Calgary": "calgary",
  "Cambridge": "cambridge",
  "Caracas": "caracas",
  "Cardiff": "cardiff",
  "Casablanca": "casablanca",
  "Charleston": "charleston",
  "Charlotte": "charlotte",
  "Chattanooga": "chattanooga",
  "Chennai": "chennai",
  "Chiang Mai": "chiang-mai",
  "Chisinau": "chisinau",
  "Christchurch": "christchurch",
  "Cincinnati": "cincinnati",
  "Cleveland": "cleveland",
  "Cluj-Napoca": "cluj-napoca",
  "Cologne": "cologne",
  "Colorado Springs": "colorado-springs",
  "Columbus": "columbus",
  "Copenhagen": "copenhagen",
  "Cork": "cork",
  "Curitiba": "curitiba",
  "Dallas": "dallas",
  "Dar es Salaam": "dar-es-salaam",
  "Denver": "denver",
  "Des Moines": "des-moines",
  "Detroit": "detroit",
  "Doha": "doha",
  "Dresden": "dresden",
  "Dublin": "dublin",
  "Dusseldorf": "dusseldorf",
  "Edinburgh": "edinburgh",
  "Edmonton": "edmonton",
  "Eindhoven": "eindhoven",
  "Eugene": "eugene",
  "Florence": "florence",
  "Florianopolis": "florianopolis",
  "Fort Collins": "fort-collins",
  "Frankfurt": "frankfurt",
  "Fukuoka": "fukuoka",
  "Galway": "gaillimh",
  "Gdansk": "gdansk",
  "Geneva": "geneva",
  "Gibraltar": "gibraltar",
  "Glasgow": "glasgow",
  "Gothenburg": "gothenburg",
  "Grenoble": "grenoble",
  "Guadalajara": "guadalajara",
  "Guatemala City": "guatemala-city",
  "Halifax": "halifax",
  "Hamburg": "hamburg",
  "Hannover": "hannover",
  "Havana": "havana",
  "Helsinki": "helsinki",
  "Ho Chi Minh City": "ho-chi-minh-city",
  "Hong Kong": "hong-kong",
  "Honolulu": "honolulu",
  "Hyderabad": "hyderabad",
  "Indianapolis": "indianapolis",
  "Innsbruck": "innsbruck",
  "Jacksonville": "jacksonville",
  "Kansas City": "kansas-city",
  "Karlsruhe": "karlsruhe",
  "Kathmandu": "kathmandu",
  "Kingston": "kingston",
  "Knoxville": "knoxville",
  "Krakow": "krakow",
  "Kuala Lumpur": "kuala-lumpur",
  "Kyoto": "kyoto",
  "La Paz": "la-paz",
  "Las Palmas de Gran Canaria": "las-palmas-de-gran-canaria",
  "Las Vegas": "las-vegas",
  "Lausanne": "lausanne",
  "Leeds": "leeds",
  "Leipzig": "leipzig",
  "Lille": "lille",
  "Lisbon": "lisbon",
  "Liverpool": "liverpool",
  "Ljubljana": "ljubljana",
  "Louisville": "louisville",
  "Luxembourg": "luxembourg",
  "Lviv": "lviv",
  "Lyon": "lyon",
  "Madison": "madison",
  "Malaga": "malaga",
  "Malmo": "malmo",
  "Managua": "managua",
  "Manchester": "manchester",
  "Marseille": "marseille",
  "Medellin": "medellin",
  "Melbourne": "melbourne",
  "Memphis": "memphis",
  "Miami": "miami",
  "Milan": "milan",
  "Milwaukee": "milwaukee",
  "Minneapolis-Saint Paul": "minneapolis-saint-paul",
  "Minsk": "minsk",
  "Montevideo": "montevideo",
  "Montreal": "montreal",
  "Munich": "munich",
  "Nairobi": "nairobi",
  "Nantes": "nantes",
  "Naples": "naples",
  "Nashville": "nashville",
  "New Orleans": "new-orleans",
  "Nice": "nice",
  "Nicosia": "nicosia",
  "Oklahoma City": "oklahoma-city",
  "Omaha": "omaha",
  "Orlando": "orlando",
  "Osaka": "osaka",
  "Oslo": "oslo",
  "Ottawa": "ottawa",
  "Oulu": "oulu",
  "Oxford": "oxford",
  "Palo Alto": "palo-alto",
  "Panama": "panama",
  "Paris": "paris",
  "Perth": "perth",
  "Philadelphia": "philadelphia",
  "Phnom Penh": "phnom-penh",
  "Phoenix": "phoenix",
  "Phuket": "phuket",
  "Pittsburgh": "pittsburgh",
  "Portland, ME": "portland-me",
  "Portland, OR": "portland-or",
  "Porto": "porto",
  "Porto Alegre": "porto-alegre",
  "Prague": "prague",
  "Providence": "providence",
  "Quebec": "quebec",
  "Quito": "quito",
  "Raleigh": "raleigh",
  "Reykjavik": "reykjavik",
  "Richmond": "richmond",
  "Riga": "riga",
  "Riyadh": "riyadh",
  "Rochester": "rochester",
  "Rome": "rome",
  "Rotterdam": "rotterdam",
  "Salt Lake City": "salt-lake-city",
  "San Antonio": "san-antonio",
  "San Diego": "san-diego",
  "San Francisco": "san-francisco-bay-area",
  "San Jose": "san-jose",
  "San Juan": "san-juan",
  "San Luis Obispo": "san-luis-obispo",
  "San Salvador": "san-salvador",
  "Santiago": "santiago",
  "Santo Domingo": "santo-domingo",
  "Sarajevo": "sarajevo",
  "Saskatoon": "saskatoon",
  "Seattle": "seattle",
  "Seoul": "seoul",
  "Seville": "seville",
  "Singapore": "singapore",
  "Skopje": "skopje",
  "Sofia": "sofia",
  "St. Louis": "st-louis",
  "Stockholm": "stockholm",
  "Stuttgart": "stuttgart",
  "Taipei": "taipei",
  "Tallinn": "tallinn",
  "Tampa Bay Area": "tampa-bay-area",
  "Tampere": "tampere",
  "Tartu": "tartu",
  "Tashkent": "tashkent",
  "Tbilisi": "tbilisi",
  "Tehran": "tehran",
  "Tel Aviv": "tel-aviv",
  "The Hague": "the-hague",
  "Thessaloniki": "thessaloniki",
  "Toulouse": "toulouse",
  "Tunis": "tunis",
  "Turin": "turin",
  "Turku": "turku",
  "Uppsala": "uppsala",
  "Utrecht": "utrecht",
  "Valencia": "valencia",
  "Valletta": "valletta",
  "Vancouver": "vancouver",
  "Victoria": "victoria",
  "Vienna": "vienna",
  "Vilnius": "vilnius",
  "Warsaw": "warsaw",
  "Washington, D.C.": "washington-dc",
  "Wellington": "wellington",
  "Winnipeg": "winnipeg",
  "Wroclaw": "wroclaw",
  "Yerevan": "yerevan",
  "Zagreb": "zagreb",
  "Zurich": "zurich"
}

const INITIALCITIES = {
  
  "Bangkok": "bangkok",
  "Beijing": "beijing" ,
  "Berlin": "berlin",
  "Buenos Aires": "buenos-aires",
  "Cairo": "cairo",
  "Cape Town": "cape-town",
  "Chicago": "chicago",
  "Delhi": "delhi",
  "Dubai": "dubai",
  "Houston": "houston",
  "Istanbul": "istanbul",
  "Jakarta": "jakarta",
  "Johannesburg": "johannesburg",
  "Kiev": "kiev",
  "Lagos": "lagos",
  "Lima": "lima",
  "London": "london",
  "Los Angeles": "los-angeles",
  "Madrid": "madrid",
  "Manila": "manila",
  "Mexico City": "mexico-city",
  "Moscow": "moscow",
  "Mumbai": "mumbai",
  "New York": "new-york",
  "Rio De Janeiro": "rio-de-janeiro",
  "Saint Petersburg": "saint-petersburg",
  "Sao Paulo": "sao-paulo",
  "Shanghai": "shanghai",
  "Sydney": "sydney",
  "Tokyo": "tokyo",
  "Toronto": "toronto",
}